/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountItem {
  'id' : ItemId,
  'name' : string,
  'memberCount' : bigint,
  'itemType' : ItemType,
  'selected' : boolean,
  'subscriberCount' : bigint,
}
export interface AuthState {
  'sessionString' : string,
  'verified' : boolean,
  'phone' : string,
}
export type ItemId = string;
export interface ItemProgress {
  'status' : JobStatus,
  'itemId' : ItemId,
  'errorMessage' : [] | [string],
  'itemName' : string,
  'itemType' : ItemType,
  'progressPct' : bigint,
}
export type ItemType = { 'bot' : null } |
  { 'chat' : null } |
  { 'group' : null } |
  { 'channel' : null } |
  { 'folder' : null };
export type JobId = string;
export type JobStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'failed' : null } |
  { 'running' : null };
export interface LogEntry {
  'startTime' : Timestamp,
  'status' : JobStatus,
  'itemId' : ItemId,
  'endTime' : [] | [Timestamp],
  'errorMessage' : [] | [string],
  'itemName' : string,
  'itemType' : ItemType,
}
export interface Session {
  'id' : SessionId,
  'createdAt' : Timestamp,
  'step' : WizardStep,
  'updatedAt' : Timestamp,
  'accountA' : AuthState,
  'accountB' : AuthState,
}
export type SessionId = string;
export type Timestamp = bigint;
export interface TransferJob {
  'id' : JobId,
  'status' : JobStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'sessionId' : SessionId,
  'items' : Array<ItemProgress>,
}
export type WizardStep = bigint;
export interface _SERVICE {
  'addLogEntry' : ActorMethod<[SessionId, LogEntry], undefined>,
  'createSession' : ActorMethod<[], SessionId>,
  'createTransferJob' : ActorMethod<[SessionId], [] | [JobId]>,
  'getScannedItems' : ActorMethod<[SessionId], Array<AccountItem>>,
  'getSession' : ActorMethod<[SessionId], [] | [Session]>,
  'getTransferJob' : ActorMethod<[JobId], [] | [TransferJob]>,
  'getTransferLogs' : ActorMethod<[SessionId], Array<LogEntry>>,
  'listTransferJobs' : ActorMethod<[SessionId], Array<TransferJob>>,
  'scanAccountA' : ActorMethod<[SessionId], Array<AccountItem>>,
  'selectAllItems' : ActorMethod<[SessionId, boolean], boolean>,
  'setAccountAAuth' : ActorMethod<[SessionId, AuthState], boolean>,
  'setAccountBAuth' : ActorMethod<[SessionId, AuthState], boolean>,
  'setWizardStep' : ActorMethod<[SessionId, WizardStep], boolean>,
  'toggleItemSelection' : ActorMethod<[SessionId, ItemId], boolean>,
  'updateItemProgress' : ActorMethod<
    [JobId, ItemId, JobStatus, bigint, [] | [string]],
    boolean
  >,
  'updateJobStatus' : ActorMethod<[JobId, JobStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];