/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const Timestamp = IDL.Int;
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
});
export const ItemId = IDL.Text;
export const ItemType = IDL.Variant({
  'bot' : IDL.Null,
  'chat' : IDL.Null,
  'group' : IDL.Null,
  'channel' : IDL.Null,
  'folder' : IDL.Null,
});
export const LogEntry = IDL.Record({
  'startTime' : Timestamp,
  'status' : JobStatus,
  'itemId' : ItemId,
  'endTime' : IDL.Opt(Timestamp),
  'errorMessage' : IDL.Opt(IDL.Text),
  'itemName' : IDL.Text,
  'itemType' : ItemType,
});
export const JobId = IDL.Text;
export const AccountItem = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'itemType' : ItemType,
  'selected' : IDL.Bool,
  'subscriberCount' : IDL.Nat,
});
export const WizardStep = IDL.Nat;
export const AuthState = IDL.Record({
  'sessionString' : IDL.Text,
  'verified' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'createdAt' : Timestamp,
  'step' : WizardStep,
  'updatedAt' : Timestamp,
  'accountA' : AuthState,
  'accountB' : AuthState,
});
export const ItemProgress = IDL.Record({
  'status' : JobStatus,
  'itemId' : ItemId,
  'errorMessage' : IDL.Opt(IDL.Text),
  'itemName' : IDL.Text,
  'itemType' : ItemType,
  'progressPct' : IDL.Nat,
});
export const TransferJob = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'sessionId' : SessionId,
  'items' : IDL.Vec(ItemProgress),
});

export const idlService = IDL.Service({
  'addLogEntry' : IDL.Func([SessionId, LogEntry], [], []),
  'createSession' : IDL.Func([], [SessionId], []),
  'createTransferJob' : IDL.Func([SessionId], [IDL.Opt(JobId)], []),
  'getScannedItems' : IDL.Func([SessionId], [IDL.Vec(AccountItem)], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
  'getTransferJob' : IDL.Func([JobId], [IDL.Opt(TransferJob)], ['query']),
  'getTransferLogs' : IDL.Func([SessionId], [IDL.Vec(LogEntry)], ['query']),
  'listTransferJobs' : IDL.Func([SessionId], [IDL.Vec(TransferJob)], ['query']),
  'scanAccountA' : IDL.Func([SessionId], [IDL.Vec(AccountItem)], []),
  'selectAllItems' : IDL.Func([SessionId, IDL.Bool], [IDL.Bool], []),
  'setAccountAAuth' : IDL.Func([SessionId, AuthState], [IDL.Bool], []),
  'setAccountBAuth' : IDL.Func([SessionId, AuthState], [IDL.Bool], []),
  'setWizardStep' : IDL.Func([SessionId, WizardStep], [IDL.Bool], []),
  'toggleItemSelection' : IDL.Func([SessionId, ItemId], [IDL.Bool], []),
  'updateItemProgress' : IDL.Func(
      [JobId, ItemId, JobStatus, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateJobStatus' : IDL.Func([JobId, JobStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const Timestamp = IDL.Int;
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
  });
  const ItemId = IDL.Text;
  const ItemType = IDL.Variant({
    'bot' : IDL.Null,
    'chat' : IDL.Null,
    'group' : IDL.Null,
    'channel' : IDL.Null,
    'folder' : IDL.Null,
  });
  const LogEntry = IDL.Record({
    'startTime' : Timestamp,
    'status' : JobStatus,
    'itemId' : ItemId,
    'endTime' : IDL.Opt(Timestamp),
    'errorMessage' : IDL.Opt(IDL.Text),
    'itemName' : IDL.Text,
    'itemType' : ItemType,
  });
  const JobId = IDL.Text;
  const AccountItem = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'itemType' : ItemType,
    'selected' : IDL.Bool,
    'subscriberCount' : IDL.Nat,
  });
  const WizardStep = IDL.Nat;
  const AuthState = IDL.Record({
    'sessionString' : IDL.Text,
    'verified' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'createdAt' : Timestamp,
    'step' : WizardStep,
    'updatedAt' : Timestamp,
    'accountA' : AuthState,
    'accountB' : AuthState,
  });
  const ItemProgress = IDL.Record({
    'status' : JobStatus,
    'itemId' : ItemId,
    'errorMessage' : IDL.Opt(IDL.Text),
    'itemName' : IDL.Text,
    'itemType' : ItemType,
    'progressPct' : IDL.Nat,
  });
  const TransferJob = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'sessionId' : SessionId,
    'items' : IDL.Vec(ItemProgress),
  });
  
  return IDL.Service({
    'addLogEntry' : IDL.Func([SessionId, LogEntry], [], []),
    'createSession' : IDL.Func([], [SessionId], []),
    'createTransferJob' : IDL.Func([SessionId], [IDL.Opt(JobId)], []),
    'getScannedItems' : IDL.Func(
        [SessionId],
        [IDL.Vec(AccountItem)],
        ['query'],
      ),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
    'getTransferJob' : IDL.Func([JobId], [IDL.Opt(TransferJob)], ['query']),
    'getTransferLogs' : IDL.Func([SessionId], [IDL.Vec(LogEntry)], ['query']),
    'listTransferJobs' : IDL.Func(
        [SessionId],
        [IDL.Vec(TransferJob)],
        ['query'],
      ),
    'scanAccountA' : IDL.Func([SessionId], [IDL.Vec(AccountItem)], []),
    'selectAllItems' : IDL.Func([SessionId, IDL.Bool], [IDL.Bool], []),
    'setAccountAAuth' : IDL.Func([SessionId, AuthState], [IDL.Bool], []),
    'setAccountBAuth' : IDL.Func([SessionId, AuthState], [IDL.Bool], []),
    'setWizardStep' : IDL.Func([SessionId, WizardStep], [IDL.Bool], []),
    'toggleItemSelection' : IDL.Func([SessionId, ItemId], [IDL.Bool], []),
    'updateItemProgress' : IDL.Func(
        [JobId, ItemId, JobStatus, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateJobStatus' : IDL.Func([JobId, JobStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };