/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type WizardStep = bigint;
export interface ItemProgress {
    status: JobStatus;
    itemId: ItemId;
    errorMessage?: string;
    itemName: string;
    itemType: ItemType;
    progressPct: bigint;
}
export type Timestamp = bigint;
export interface TransferJob {
    id: JobId;
    status: JobStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    sessionId: SessionId;
    items: Array<ItemProgress>;
}
export interface Session {
    id: SessionId;
    createdAt: Timestamp;
    step: WizardStep;
    updatedAt: Timestamp;
    accountA: AuthState;
    accountB: AuthState;
}
export interface LogEntry {
    startTime: Timestamp;
    status: JobStatus;
    itemId: ItemId;
    endTime?: Timestamp;
    errorMessage?: string;
    itemName: string;
    itemType: ItemType;
}
export type ItemId = string;
export interface AccountItem {
    id: ItemId;
    name: string;
    memberCount: bigint;
    itemType: ItemType;
    selected: boolean;
    subscriberCount: bigint;
}
export type JobId = string;
export type SessionId = string;
export interface AuthState {
    sessionString: string;
    verified: boolean;
    phone: string;
}
export enum ItemType {
    bot = "bot",
    chat = "chat",
    group = "group",
    channel = "channel",
    folder = "folder"
}
export enum JobStatus {
    pending = "pending",
    complete = "complete",
    failed = "failed",
    running = "running"
}
export interface backendInterface {
    addLogEntry(sessionId: SessionId, entry: LogEntry): Promise<void>;
    createSession(): Promise<SessionId>;
    createTransferJob(sessionId: SessionId): Promise<JobId | null>;
    getScannedItems(sessionId: SessionId): Promise<Array<AccountItem>>;
    getSession(sessionId: SessionId): Promise<Session | null>;
    getTransferJob(jobId: JobId): Promise<TransferJob | null>;
    getTransferLogs(sessionId: SessionId): Promise<Array<LogEntry>>;
    listTransferJobs(sessionId: SessionId): Promise<Array<TransferJob>>;
    scanAccountA(sessionId: SessionId): Promise<Array<AccountItem>>;
    selectAllItems(sessionId: SessionId, selected: boolean): Promise<boolean>;
    sendCode(sessionId: SessionId, phone: string, account: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAccountAAuth(sessionId: SessionId, auth: AuthState): Promise<boolean>;
    setAccountBAuth(sessionId: SessionId, auth: AuthState): Promise<boolean>;
    setWizardStep(sessionId: SessionId, step: WizardStep): Promise<boolean>;
    toggleItemSelection(sessionId: SessionId, itemId: ItemId): Promise<boolean>;
    updateItemProgress(jobId: JobId, itemId: ItemId, status: JobStatus, progressPct: bigint, errorMessage: string | null): Promise<boolean>;
    updateJobStatus(jobId: JobId, status: JobStatus): Promise<boolean>;
    verifyCode(sessionId: SessionId, phone: string, code: string, account: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            initials: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AccountItem as _AccountItem, ItemId as _ItemId, ItemProgress as _ItemProgress, ItemType as _ItemType, JobId as _JobId, JobStatus as _JobStatus, LogEntry as _LogEntry, Session as _Session, SessionId as _SessionId, Timestamp as _Timestamp, TransferJob as _TransferJob } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLogEntry(arg0: SessionId, arg1: LogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogEntry(arg0, to_candid_LogEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogEntry(arg0, to_candid_LogEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSession(): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession();
            return result;
        }
    }
    async createTransferJob(arg0: SessionId): Promise<JobId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransferJob(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransferJob(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScannedItems(arg0: SessionId): Promise<Array<AccountItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScannedItems(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScannedItems(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: SessionId): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransferJob(arg0: JobId): Promise<TransferJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransferJob(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransferJob(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransferLogs(arg0: SessionId): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransferLogs(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransferLogs(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransferJobs(arg0: SessionId): Promise<Array<TransferJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransferJobs(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransferJobs(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async scanAccountA(arg0: SessionId): Promise<Array<AccountItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.scanAccountA(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanAccountA(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async selectAllItems(arg0: SessionId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.selectAllItems(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectAllItems(arg0, arg1);
            return result;
        }
    }
    async sendCode(arg0: SessionId, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCode(arg0, arg1, arg2);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCode(arg0, arg1, arg2);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAccountAAuth(arg0: SessionId, arg1: AuthState): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountAAuth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountAAuth(arg0, arg1);
            return result;
        }
    }
    async setAccountBAuth(arg0: SessionId, arg1: AuthState): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountBAuth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountBAuth(arg0, arg1);
            return result;
        }
    }
    async setWizardStep(arg0: SessionId, arg1: WizardStep): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setWizardStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWizardStep(arg0, arg1);
            return result;
        }
    }
    async toggleItemSelection(arg0: SessionId, arg1: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleItemSelection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleItemSelection(arg0, arg1);
            return result;
        }
    }
    async updateItemProgress(arg0: JobId, arg1: ItemId, arg2: JobStatus, arg3: bigint, arg4: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItemProgress(arg0, arg1, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItemProgress(arg0, arg1, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateJobStatus(arg0: JobId, arg1: JobStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyCode(arg0: SessionId, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            initials: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCode(arg0, arg1, arg2, arg3);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCode(arg0, arg1, arg2, arg3);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountItem_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountItem): AccountItem {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ItemProgress_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemProgress): ItemProgress {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LogEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogEntry): LogEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TransferJob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferJob): TransferJob {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransferJob]): TransferJob | null {
    return value.length === 0 ? null : from_candid_TransferJob_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobId]): JobId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    name: string;
    memberCount: bigint;
    itemType: _ItemType;
    selected: boolean;
    subscriberCount: bigint;
}): {
    id: ItemId;
    name: string;
    memberCount: bigint;
    itemType: ItemType;
    selected: boolean;
    subscriberCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        memberCount: value.memberCount,
        itemType: from_candid_ItemType_n11(_uploadFile, _downloadFile, value.itemType),
        selected: value.selected,
        subscriberCount: value.subscriberCount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    sessionId: _SessionId;
    items: Array<_ItemProgress>;
}): {
    id: JobId;
    status: JobStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    sessionId: SessionId;
    items: Array<ItemProgress>;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n17(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        sessionId: value.sessionId,
        items: from_candid_vec_n19(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    itemId: _ItemId;
    errorMessage: [] | [string];
    itemName: string;
    itemType: _ItemType;
    progressPct: bigint;
}): {
    status: JobStatus;
    itemId: ItemId;
    errorMessage?: string;
    itemName: string;
    itemType: ItemType;
    progressPct: bigint;
} {
    return {
        status: from_candid_JobStatus_n17(_uploadFile, _downloadFile, value.status),
        itemId: value.itemId,
        errorMessage: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.errorMessage)),
        itemName: value.itemName,
        itemType: from_candid_ItemType_n11(_uploadFile, _downloadFile, value.itemType),
        progressPct: value.progressPct
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Timestamp;
    status: _JobStatus;
    itemId: _ItemId;
    endTime: [] | [_Timestamp];
    errorMessage: [] | [string];
    itemName: string;
    itemType: _ItemType;
}): {
    startTime: Timestamp;
    status: JobStatus;
    itemId: ItemId;
    endTime?: Timestamp;
    errorMessage?: string;
    itemName: string;
    itemType: ItemType;
} {
    return {
        startTime: value.startTime,
        status: from_candid_JobStatus_n17(_uploadFile, _downloadFile, value.status),
        itemId: value.itemId,
        endTime: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.endTime)),
        errorMessage: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.errorMessage)),
        itemName: value.itemName,
        itemType: from_candid_ItemType_n11(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bot: null;
} | {
    chat: null;
} | {
    group: null;
} | {
    channel: null;
} | {
    folder: null;
}): ItemType {
    return "bot" in value ? ItemType.bot : "chat" in value ? ItemType.chat : "group" in value ? ItemType.group : "channel" in value ? ItemType.channel : "folder" in value ? ItemType.folder : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    failed: null;
} | {
    running: null;
}): JobStatus {
    return "pending" in value ? JobStatus.pending : "complete" in value ? JobStatus.complete : "failed" in value ? JobStatus.failed : "running" in value ? JobStatus.running : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        username: string;
        initials: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        username: string;
        initials: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ItemProgress>): Array<ItemProgress> {
    return value.map((x)=>from_candid_ItemProgress_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogEntry>): Array<LogEntry> {
    return value.map((x)=>from_candid_LogEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransferJob>): Array<TransferJob> {
    return value.map((x)=>from_candid_TransferJob_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccountItem>): Array<AccountItem> {
    return value.map((x)=>from_candid_AccountItem_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ItemType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LogEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogEntry): _LogEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Timestamp;
    status: JobStatus;
    itemId: ItemId;
    endTime?: Timestamp;
    errorMessage?: string;
    itemName: string;
    itemType: ItemType;
}): {
    startTime: _Timestamp;
    status: _JobStatus;
    itemId: _ItemId;
    endTime: [] | [_Timestamp];
    errorMessage: [] | [string];
    itemName: string;
    itemType: _ItemType;
} {
    return {
        startTime: value.startTime,
        status: to_candid_JobStatus_n3(_uploadFile, _downloadFile, value.status),
        itemId: value.itemId,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        errorMessage: value.errorMessage ? candid_some(value.errorMessage) : candid_none(),
        itemName: value.itemName,
        itemType: to_candid_ItemType_n5(_uploadFile, _downloadFile, value.itemType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    pending: null;
} | {
    complete: null;
} | {
    failed: null;
} | {
    running: null;
} {
    return value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.complete ? {
        complete: null
    } : value == JobStatus.failed ? {
        failed: null
    } : value == JobStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    bot: null;
} | {
    chat: null;
} | {
    group: null;
} | {
    channel: null;
} | {
    folder: null;
} {
    return value == ItemType.bot ? {
        bot: null
    } : value == ItemType.chat ? {
        chat: null
    } : value == ItemType.group ? {
        group: null
    } : value == ItemType.channel ? {
        channel: null
    } : value == ItemType.folder ? {
        folder: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
